import os

CHATGPT_MODEL = "gpt-4o-mini"
CHATGPT_TEMPERATURE = 0.5

IRRELEVANT_MESSAGE_LIMIT = 2

REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
ROLEPLAY_SESSION_TTL_SECONDS = int(os.getenv("ROLEPLAY_SESSION_TTL_SECONDS", "86400"))
ROLEPLAY_LOCK_TIMEOUT_SECONDS = int(os.getenv("ROLEPLAY_LOCK_TIMEOUT_SECONDS", "60"))
ROLEPLAY_LOCK_BLOCKING_TIMEOUT_SECONDS = int(
    os.getenv("ROLEPLAY_LOCK_BLOCKING_TIMEOUT_SECONDS", "15")
)
