/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/roleplay/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_roleplay_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConversationMessage */
        ConversationMessage: {
            /**
             * Role
             * @description Speaker role: 'learner' or 'ai_character'.
             * @enum {string}
             */
            role: "learner" | "ai_character";
            /**
             * Content
             * @description Message content for this turn.
             */
            content: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RoleplayRequest */
        RoleplayRequest: {
            /**
             * Scenario
             * @description The roleplay scenario and setting.
             * @example You are at a car dealership negotiating the price of a used sedan.
             */
            scenario: string;
            /**
             * Learner Goals
             * @description Goals the learner should practice during the roleplay.
             * @example [
             *       "Negotiate a fair price",
             *       "Ask about warranty options"
             *     ]
             */
            learner_goals: string[];
            /**
             * Learner Role
             * @description The role the learner is playing.
             * @example A first-time car buyer
             */
            learner_role: string;
            /**
             * Learner Message
             * @description The learner's latest message in the conversation.
             * @example Hi, I'm interested in this car. What's your best price?
             */
            learner_message: string;
            /**
             * Ai Character Name
             * @description Name of the AI character.
             * @example Alex
             */
            ai_character_name: string;
            /**
             * Ai Character Role
             * @description Role the AI character is playing.
             * @example Experienced car salesperson
             */
            ai_character_role: string;
            /**
             * Ai Character Personality
             * @description Personality traits and tone for the AI character.
             * @example Friendly but persuasive, focused on closing the deal.
             */
            ai_character_personality: string;
            /**
             * Conversation History
             * @description Prior turns in the conversation, oldest first.
             */
            conversation_history?: components["schemas"]["ConversationMessage"][];
        };
        /** RoleplayResponse */
        RoleplayResponse: {
            /**
             * Ai Character Name
             * @description Name of the AI character that responded.
             */
            ai_character_name: string;
            /**
             * Ai Response
             * @description The AI character's reply to the learner's message.
             */
            ai_response: string;
            /**
             * Should End
             * @description Whether the roleplay conversation should end.
             */
            should_end: boolean;
            /**
             * Ending Condition
             * @description Primary reason the conversation should end, or 'none'.
             * @enum {string}
             */
            ending_condition: "goals_achieved" | "profanity" | "conversation_exhausted" | "irrelevant" | "none";
            /**
             * Ending Rationale
             * @description Brief explanation of the ending evaluation.
             */
            ending_rationale: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_roleplay_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleplayRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleplayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
