/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/roleplays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Roleplay */
        post: operations["create_roleplay_roleplays_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roleplays/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Stream
         * @description Stream the AI reply as SSE (`token` events, then a final `done` event).
         */
        post: operations["chat_stream_roleplays_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CreateRoleplayRequest
         * @description Start a new practice session: send setup only.
         */
        CreateRoleplayRequest: {
            /**
             * Scenario
             * @description The roleplay scenario and setting.
             * @example You are at a car dealership negotiating the price of a used sedan.
             */
            scenario: string;
            /**
             * Learner Role
             * @description The role the learner is playing.
             * @example A first-time car buyer
             */
            learner_role: string;
            /**
             * Learner Goals
             * @description Goals the learner should practice during the roleplay.
             * @example [
             *       "Negotiate a fair price",
             *       "Ask about warranty options"
             *     ]
             */
            learner_goals: string[];
            /**
             * Ai Character Name
             * @description Name of the AI character.
             * @example Alex
             */
            ai_character_name: string;
            /**
             * Ai Character Role
             * @description Role the AI character is playing.
             * @example Experienced car salesperson
             */
            ai_character_role: string;
            /**
             * Ai Character Personality
             * @description Personality traits and tone for the AI character.
             * @example Friendly but persuasive, focused on closing the deal.
             */
            ai_character_personality: string;
        };
        /**
         * CreateRoleplayResponse
         * @description Returned after a session is created.
         */
        CreateRoleplayResponse: {
            /**
             * Roleplay Id
             * @description Id of the newly created roleplay session.
             */
            roleplay_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * RoleplayChatRequest
         * @description Continue a session: send only the session id and the new learner message.
         */
        RoleplayChatRequest: {
            /**
             * Roleplay Id
             * @description Id of the roleplay session in cache.
             */
            roleplay_id: string;
            /**
             * Learner Message
             * @description The learner's latest message in the conversation.
             * @example Hi, I'm interested in this car. What's your best price?
             */
            learner_message: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_roleplay_roleplays_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleplayRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRoleplayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_roleplays_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleplayChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
